#Fire (User Fire + collect coordinates)
#Random Fire (CPU Fire(choose + collect coordinates))
#Fire Warning (have you chosen these coordinates before? Loop)
#Collect Fire response (Coordinates hit or miss[display on board])
#Collect Shots Taken (Guesses)
